enable windows builds and tests

diff --git a/.github/workflows/_build.yml b/.github/workflows/_build.yml
--- a/.github/workflows/_build.yml
+++ b/.github/workflows/_build.yml
@@ -1,6 +1,6 @@
 # -*- coding: utf-8 -*-
 # Copyright (C) 2023 Benjamin Thomas Schwertfeger
-# Github: https://github.com/btschwertfeger
+# GitHub: https://github.com/btschwertfeger
 #
 # Template workflow to build the project for a specific os
 # and Python version.
@@ -33,9 +33,22 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
+          python -m pip install build
 
       - name: Build the package
-        run: python -m pip wheel -w dist --no-deps .
+        run: python -m build --outdir .
 
-      - name: Install the package
-        run: python3 -m pip install dist/python_cmethods*.whl
+      - name: Install the package on Linux or MacOS
+        if: runner.os != 'Windows'
+        run: python -m pip install python_cmethods*.whl
+
+      - name: Install the package on Windows
+        if: runner.os == 'Windows'
+        run: |
+          try {
+              $WHEEL = Get-ChildItem -Path . -Filter "python_cmethods*.whl" -ErrorAction Stop
+              python -m pip install $WHEEL
+          } catch {
+              Write-Error "Error: .whl file not found in the current directory."
+              exit 1
+          }
